### ISSUE TITLE
Inconsistent experimental results and descripitions

### ISSUE THREAD

**Issue by familyld** [CRIPAC-DIG/SR-GNN#11]
Please check Figure 4 in the STAMP paper.
The data reported in Table 3 in your paper is quite different with the data reported in Figure 4 even with the same experimental settings. To be specific, in Table 3, the P@20 of  STAMP on Diginetica is 47.26 and 40.39 for short sessions and long sessions respectively. However, the data reported in Figure 4 is around 61 and 65 respectively. STAMP actually performs better with long seesions on Diginetica. Why the big difference between your experiments and Qiao Liu's?

**Comment by SXKDZ** [comment]
Hello, thanks for your interest on our paper.

In prior to attending the conference, someone notices us that there might be a small but lethal mistake when we preprocess the DIGENTICA dataset of CIKM Cup 16. At that time we only sort the DIGENTICA dataset by `eventdate` in `train-item-views.csv`, since we directly make use of public code made by NARM’s authors. However, user clicks within every user session in the original dataset are still out of order, whereas the relative order of user clicks are specified in the `timeframe` field. Therefore, we contact the authors of NARM and find that they report their performance for the Diginetica dataset undergone the above wrong data preprocessing procedure.

I believe the subsequent work STAMP copy results of NARM and his performance is also based on the wrong dataset. I also try to reproduce the performance of STAMP based on the corrected dataset but sadly both two performance indicators (i.e. Precision@20 and MRR@20) drop GREATLY and are lower than NARM’s correct performance. I try to contact STAMP’s author but receive no response. Therefore, I report his performance based on my own implementations.

**Comment by familyld** [comment]
Good to know, BTW, nice work!
Thanks.
