### ISSUE TITLE
why diginetica dataset just sorted by eventdate not timeframe?

### ISSUE THREAD

**Issue by ibunny01** [CRIPAC-DIG/SR-GNN#3]
Hi, I found that in your 'preprocess.py' file, you just sorted the diginetica dataset by `eventdate` (%Y-%m-%d), I got a little confused because if you don't sort it by `timeframe`, in each session those item click stream is still out of order?

**Comment by SXKDZ** [comment]
Thank you for your meticulous observations. The root cause of this problem is that we use the same preprocessing procudure as NARM's. (I believe you must have noticed this.) Also, STAMP's preprocessing on DIGENTICA data made the same mistake. Thereby, the performance of all baselines currently is on a wrong basis. We will update the code and the corresponding performance in the final version of the paper. After the conference proceeding comes out we will also upload it to arXiv. Please keep an eye on. Thanks again.
